name: Deploy

on:
  push:
    branches:
      - master

# Concurrency group ensures only one deployment to Pages runs at a time
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      # 1. Install & configure Deno v2.x
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      # 2. Install npm dependencies listed in package.json
      - run: deno install

      # 3. Execute the SSG build step configured in deno.json
      - run: deno task build

      # Packaging and uploading the artifact specifically for GitHub Pages
      - uses: actions/upload-pages-artifact@v3
        with:
          path: generated

  # 2. Parallel job to publish directly to GitHub Pages
  deploy-pages:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write # Required to write to Pages
      id-token: write # Required to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
