name: Deploy

on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: ./gradle run
      - uses: actions/upload-artifact@v7
        with:
          path: generated